### ISSUE TITLE
Package Dead

### ISSUE THREAD

**Issue by michael-letcher** [hardikpthv/vscode-ngrx-snippets#3]
Is this package dead?

**Comment by hardikpthv** [comment]
@michael-letcher, it is not dead. You can create the issues and MRs for new features if needed.

**Comment by michael-letcher** [comment]
@hardikpthv 
Do I need a ticket to get my 7 month old MR to get looked at?

**Comment by hardikpthv** [comment]
Apologies @michael-letcher for the delay due to unavoidable circumstances. I will merge your changes and publish it. Thank your for contributing :)
